// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using back_end.Data;

#nullable disable

namespace back_end.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610014607_SetupMigration")]
    partial class SetupMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArtistTitle", b =>
                {
                    b.Property<int>("Artistid")
                        .HasColumnType("integer");

                    b.Property<int>("Titleid")
                        .HasColumnType("integer");

                    b.HasKey("Artistid", "Titleid");

                    b.HasIndex("Titleid");

                    b.ToTable("ArtistTitle");
                });

            modelBuilder.Entity("AuthorTitle", b =>
                {
                    b.Property<int>("Authorid")
                        .HasColumnType("integer");

                    b.Property<int>("Titleid")
                        .HasColumnType("integer");

                    b.HasKey("Authorid", "Titleid");

                    b.HasIndex("Titleid");

                    b.ToTable("AuthorTitle");
                });

            modelBuilder.Entity("GenreTitle", b =>
                {
                    b.Property<int>("Genreid")
                        .HasColumnType("integer");

                    b.Property<int>("Titleid")
                        .HasColumnType("integer");

                    b.HasKey("Genreid", "Titleid");

                    b.HasIndex("Titleid");

                    b.ToTable("GenreTitle");
                });

            modelBuilder.Entity("ThemeTitle", b =>
                {
                    b.Property<int>("Themeid")
                        .HasColumnType("integer");

                    b.Property<int>("Titleid")
                        .HasColumnType("integer");

                    b.HasKey("Themeid", "Titleid");

                    b.HasIndex("Titleid");

                    b.ToTable("ThemeTitle");
                });

            modelBuilder.Entity("back_end.Models.AlternativeName", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<int>("TitleId")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("TitleId");

                    b.ToTable("AlternativeNames");
                });

            modelBuilder.Entity("back_end.Models.Artist", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("back_end.Models.Author", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("back_end.Models.Chapter", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("TitleId")
                        .HasColumnType("integer");

                    b.Property<decimal>("number")
                        .HasColumnType("decimal(5,1)");

                    b.HasKey("id");

                    b.HasIndex("TitleId", "number")
                        .IsUnique();

                    b.ToTable("Chapters", t =>
                        {
                            t.HasCheckConstraint("CK_ChapterNumber", "number >= 0");
                        });
                });

            modelBuilder.Entity("back_end.Models.ChapterTranslation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("integer");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<int>("ScanGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("chapterTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("isOfficial")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("uploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("viewCount")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ScanGroupId");

                    b.HasIndex("ChapterId", "ScanGroupId", "LanguageId")
                        .IsUnique();

                    b.ToTable("ChapterTranslations", t =>
                        {
                            t.HasCheckConstraint("CK_ChapterTranslation_ViewCount", "\"viewCount\" >= 0");
                        });
                });

            modelBuilder.Entity("back_end.Models.ContentRating", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("ContentRatings");
                });

            modelBuilder.Entity("back_end.Models.Demographic", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Demographics");
                });

            modelBuilder.Entity("back_end.Models.Genre", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("back_end.Models.Language", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("back_end.Models.ScanGroup", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("websiteUrl")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("ScanGroups");
                });

            modelBuilder.Entity("back_end.Models.Status", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("back_end.Models.Theme", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("back_end.Models.Title", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("ContentRatingId")
                        .HasColumnType("integer");

                    b.Property<int>("DemographicId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("img")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("publicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("synopsis")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.HasKey("id");

                    b.HasIndex("ContentRatingId");

                    b.HasIndex("DemographicId");

                    b.HasIndex("StatusId");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("ArtistTitle", b =>
                {
                    b.HasOne("back_end.Models.Artist", null)
                        .WithMany()
                        .HasForeignKey("Artistid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.Models.Title", null)
                        .WithMany()
                        .HasForeignKey("Titleid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AuthorTitle", b =>
                {
                    b.HasOne("back_end.Models.Author", null)
                        .WithMany()
                        .HasForeignKey("Authorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.Models.Title", null)
                        .WithMany()
                        .HasForeignKey("Titleid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreTitle", b =>
                {
                    b.HasOne("back_end.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("Genreid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.Models.Title", null)
                        .WithMany()
                        .HasForeignKey("Titleid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ThemeTitle", b =>
                {
                    b.HasOne("back_end.Models.Theme", null)
                        .WithMany()
                        .HasForeignKey("Themeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.Models.Title", null)
                        .WithMany()
                        .HasForeignKey("Titleid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("back_end.Models.AlternativeName", b =>
                {
                    b.HasOne("back_end.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("back_end.Models.Title", "Title")
                        .WithMany("AlternativeNames")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("back_end.Models.Chapter", b =>
                {
                    b.HasOne("back_end.Models.Title", "Title")
                        .WithMany("Chapters")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");
                });

            modelBuilder.Entity("back_end.Models.ChapterTranslation", b =>
                {
                    b.HasOne("back_end.Models.Chapter", "Chapter")
                        .WithMany("ChapterTranslation")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.Models.Language", "Language")
                        .WithMany("ChapterTranslation")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.Models.ScanGroup", "ScanGroup")
                        .WithMany("ChapterTranslation")
                        .HasForeignKey("ScanGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("Language");

                    b.Navigation("ScanGroup");
                });

            modelBuilder.Entity("back_end.Models.Title", b =>
                {
                    b.HasOne("back_end.Models.ContentRating", "ContentRating")
                        .WithMany("Title")
                        .HasForeignKey("ContentRatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.Models.Demographic", "Demographic")
                        .WithMany("Title")
                        .HasForeignKey("DemographicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.Models.Status", "Status")
                        .WithMany("Title")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentRating");

                    b.Navigation("Demographic");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("back_end.Models.Chapter", b =>
                {
                    b.Navigation("ChapterTranslation");
                });

            modelBuilder.Entity("back_end.Models.ContentRating", b =>
                {
                    b.Navigation("Title");
                });

            modelBuilder.Entity("back_end.Models.Demographic", b =>
                {
                    b.Navigation("Title");
                });

            modelBuilder.Entity("back_end.Models.Language", b =>
                {
                    b.Navigation("ChapterTranslation");
                });

            modelBuilder.Entity("back_end.Models.ScanGroup", b =>
                {
                    b.Navigation("ChapterTranslation");
                });

            modelBuilder.Entity("back_end.Models.Status", b =>
                {
                    b.Navigation("Title");
                });

            modelBuilder.Entity("back_end.Models.Title", b =>
                {
                    b.Navigation("AlternativeNames");

                    b.Navigation("Chapters");
                });
#pragma warning restore 612, 618
        }
    }
}
